todo_api/urls.py
from django.urls import path, include
from .views import home, TodoView, TodoDetailView

app_name = 'todo_api'

urlpatterns = [
    path('home', home, name='name'),
    path('todo', TodoView.as_view(), name='todo-index'),
    path('todo/<int:pk>', TodoDetailView.as_view(), name='todo-detail'),
]

todo_app1/urls.py
from django.urls import path
from .views import index, TodoItemsView, TodoAdd, TodoDelete

app_name = 'todo_app'

urlpatterns = [
    path('', TodoItemsView, name='todo-app-index'),
    path('add/', TodoAdd, name='todo-add'),
    path('delete/<int:todo_id>/', TodoDelete, name='todo-delete'),

]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('todo_api.urls')),  # API app
    path('', include('todo_app1.urls')),  # UI app

]

todo_api/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    date_created = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=True)
    isCompleted = models.BooleanField(default=False)

    def __str__(self):
        return f'Task: {self.title}'

todo_app1/models.py
from django.db import models

# Create your models here.

todo_api/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Django rest framework
from rest_framework import generics

from .models import Todo
from .serializers import TodoSerializer


def home(request):
    return HttpResponse('Hello, world!')


class TodoView(generics.ListCreateAPIView):
    """ This view have the functionality to list or create a Task in API. """

    queryset = Todo.objects.all()
    serializer_class = TodoSerializer


class TodoDetailView(generics.RetrieveUpdateDestroyAPIView):
    """ This view will get the specific task record based on their PK that was set to pull. """

    queryset = Todo.objects.all().order_by('date_created')
    serializer_class = TodoSerializer

todo_app1/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from todo_api.models import Todo

# import the pre-built django generic view
from django.views.generic.list import ListView


def index(request):
    return HttpResponse('Hello World! this is the APP index view')

# This will display all the task created with DRF


def TodoItemsView(request):
    todo_list = Todo.objects.all().order_by('-id')
    context = {
        'todo_list': todo_list,
    }
    return render(request, 'todos/index.html', context)


def TodoAdd(request):
    title = request.POST['title']
    description = request.POST['description']

    todo = Todo.objects.create(
        title=title,
        description=description
    )

    todo.save()

    return redirect('todo_app:todo-app-index')


def TodoDelete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()

    return redirect('todo_app:todo-app-index')

templates/todos/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

    {% block content %}

    {% endblock %}

</body>
</html>

templates/todos/index.html
{% extends 'todos/base.html' %}

{% block title%} TODO-APP {% endblock %}

{% block content %}

<div class="container text-center">

    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>My Todo List:</h1>
            </div>
        </div>
    </div>

    {% comment %} Add a new Todo Task {% endcomment %}

    <div class="row" id="div-add">
            <form method="POST" action="{% url 'todo_app:todo-add' %}">
                {% csrf_token %}
                <div class="row-cols-1">
                    <input id="input-title" type="text" class="form-control" name="title" placeholder="Add a new task ..." required>
                </div>
                <div class="row-cols-1">
                    <input id="input-title" type="text" class="form-control" name="description" placeholder="Add a description...">
                </div>
                <div class="row-cols-1" id="add-button">
                    <button id="add-button" type="submit" class="btn btn-outline-primary" name="submit">Add</button>
                </div>
            </form>
    </div>
    <hr>

    {% comment %} Display the Todo List {% endcomment %}

    <div>
        {% if todo_list %}
            {% for item in todo_list %}
            <div class='border-bottom m-3'>
                <ul class='todo_task_list'>
                    <li><h4>Title: {{ item.title }}</h4></li>
                    <div class='task_descriptions'>
                        <li>Description: {{ item.description }}</li>
                        <li>Date Created: {{ item.date_created }}</li>
                        <li>Completed: {{ item.isCompleted }}</li>
                    </div>
                </ul>
            </div>
            {% empty %}
                <p>Good news! You don't have any task for now, just relax a bit and breathe!</p>
            {% endfor %}
        {% endif %}
    </div>      
</div>

{% endblock %}